# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Traqa Documentation
site_url: https://docs.traqa.io
theme:
  language: en
  name: material
  logo: assets/Traqa_Logo_White.png
  favicon: images/favicon.png
  palette:
    primary: custom
  font:
    text: Poppins
    code: Roboto Mono
  features:
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
extra_css:
  - stylesheets/extra.css
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/linkedin
      link: https://uk.linkedin.com/company/tra-traqa
      name: Traqa on LinkedIn
  generator: false
copyright: >
  Copyright &copy; 2025 Traqa –
  <a href="#__consent">Change cookie settings</a>
plugins:
  - search
  - privacy
  - tags